_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "CustomRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: SSODROIHeads
    # NAME: VLPLMROIHeads2
    NUM_CLASSES: 65
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: True
DATASETS:
  TRAIN: ("coco_openvoc_train_with_clip",)
  TEST: ('coco_openvoc_val_all', )
SOLVER:
  CHECKPOINT_PERIOD: 5000
  IMS_PER_BATCH: 16
  STEPS: (60000, 80000)
  MAX_ITER: 90001

OUTPUT_DIR: "./output/MarvelOVD"
DATALOADER:
  NUM_WORKERS: 0
TEST:
  EVAL_PERIOD: 5000