_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "CustomRCNN"
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "./output/burn_in_500.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: SSODROIHeads
    # NAME: VLPLMROIHeads2
    NUM_CLASSES: 65
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: True
DATASETS:
  TRAIN: ("coco_openvoc_train_with_clip",)
  # TRAIN: ("coco_openvoc_train",)
  # TRAIN: ("coco_openvoc_multi_stage",)
  TEST: ('coco_openvoc_val_all', )
SOLVER:
  CHECKPOINT_PERIOD: 5000000
  IMS_PER_BATCH: 16
  STEPS: (60000, 80000)
  MAX_ITER: 90001
# INPUT:
  # MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  # MIN_SIZE_TRAIN: (128, 160, 192, 224, 256, 288, 320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704,
  #   736, 768, 800, 832, 864, 896, 928, 960, 992, 1024, 1056, 1088, 1120, 1152, 1184, 1216, 1248,
  #   1280)
OUTPUT_DIR: "./output/pseudo_label_multi_reg"
DATALOADER:
  NUM_WORKERS: 0
TEST:
  EVAL_PERIOD: 5000