_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "output/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("coco_train_base_48_num1",)
  TEST: ("coco_val_base_48_num1", "coco_val_novel_17_num1")
SOLVER:
  CHECKPOINT_PERIOD: 1000
  IMS_PER_BATCH: 16
OUTPUT_DIR: "./output/faster_rcnn/auto"
DATALOADER:
  NUM_WORKERS: 16
